name: attest in various ways

on:
  push:


permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  attest-direct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1.1.1
        with:
          subject-path: foo.txt

  attest-reusable:
    uses: ./.github/workflows/attest-reusable.yml
