on:
  workflow_call:

jobs:
  attest-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1.1.1
        with:
          subject-path: foo.txt
